### PR TITLE
Remove unnecessary async keyword in hwmon handler

### PR DESCRIPTION
**Pull request by libc-furiosa**
Functions in `hwmon` module have `async` keyword but doesn't really work meaningfully. (just sequential async-await)
For convenience, it would be better to change to sync. (Some other APIs already applied)
( #41 )

### CODE REVIEW

**Comment by hyunsik** [comment]
@libc-furiosa @sukyoungjeong-furiosa 

I agree with that the IO operations are trivial and run sequentially. `async/await` may not be able to impact on performance or throughput.

To make a better decision, let's also think about their role as yield points. The reason why we use async/await is basically concurrency. In more details, async/await makes multiple tasks to run concurrently even in a single thread through cooperative multi-tasking which are based on yield control.

`async` function is a way to generate yield points implicitly and automatically. The main difference of `tokio::fs` from `std::fs` is that `tokio::fs` internally use a blocking thread pool and schedule IO operations to the blocking thread pool. So, `tokio::fs` doesn't block tokio executor and yield when any IO operation is called. 

When users develop some applications with async/await version like monitoring system using device api for dozen NPU cards, users don't have to worry about the blocking calls within async tasks. If it uses `std::fs`, they have to be concerned with the IO blocking calls within their async task.

**Comment by libc-furiosa** [comment]
Thanks for the detailed explanation. I agree with your argument.

It seems that the API needs to be improved in the near future.
I think we have two options at this point.
Whether to temporarily approve this PR and allow only blocking calls explicitly, or discard this PR and keep the existing implementation.

Please tell me your opinions.

**Comment by hyunsik** [comment]
If we are not sure, let's keep the current code.

**Comment by libc-furiosa** [comment]
Thank you. Close this PR.

**Pull request closed without merging**
